[package]
name = "hide-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true
description = "Command-line interface for the HIDE protocol: encrypt to a person, not to a key"

[[bin]]
name = "hide"
path = "src/main.rs"

[dependencies]
hide-crypto = { path = "../../crates/hide-crypto", version = "0.6.2" }
hide-keyring = { path = "../../crates/hide-keyring", version = "0.6.2" }
hide-sign = { path = "../../crates/hide-sign", version = "0.6.2" }
base64.workspace = true
rpassword.workspace = true
hide-object = { path = "../../crates/hide-object", version = "0.6.2" }
hide-identity = { path = "../../crates/hide-identity", version = "0.6.2" }
hide-epoch = { path = "../../crates/hide-epoch", version = "0.6.2" }
clap.workspace = true
tempfile.workspace = true
zeroize.workspace = true
ed25519-dalek.workspace = true
sha2.workspace = true

[target.'cfg(windows)'.dependencies]
interprocess.workspace = true

[lints]
workspace = true
