//! The desktop app and the CLI must remain one format. A change to either that
//! breaks the other is a protocol break, and this test is what catches it.

use std::{path::Path, process::Command};

/// Absolute, because the working directory of a test binary is not guaranteed.
fn cli() -> Option<std::path::PathBuf> {
    // Built by `cargo build -p hide-cli` in the main workspace, whose target
    // directory is three levels above this crate.
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../..");
    for candidate in [
        "target/debug/hide.exe",
        "target/debug/hide",
        "target/release/hide.exe",
        "target/release/hide",
    ] {
        let path = root.join(candidate);
        if path.is_file() {
            return Some(path);
        }
    }
    None
}

#[test]
fn the_desktop_app_opens_what_the_cli_sealed() {
    let Some(cli) = cli() else {
        eprintln!("skipping: the hide CLI has not been built");
        return;
    };
    let directory = tempfile::tempdir().expect("temp dir");
    let root = directory.path();

    let keygen = Command::new(&cli)
        .current_dir(root)
        .args([
            "--experimental",
            "--quiet",
            "keygen",
            "--secret",
            "a.key",
            "--public",
            "a.pub",
            "--insecure-plaintext",
        ])
        .output()
        .expect("cli runs");
    assert!(
        keygen.status.success(),
        "keygen failed: {}",
        String::from_utf8_lossy(&keygen.stderr)
    );

    let sealed = Command::new(&cli)
        .current_dir(root)
        .args([
            "--experimental",
            "--quiet",
            "seal",
            "from the command line",
            "--recipient",
            "a.pub",
        ])
        .output()
        .expect("cli runs");
    assert!(
        sealed.status.success(),
        "seal failed: {}",
        String::from_utf8_lossy(&sealed.stderr)
    );
    let armored = String::from_utf8(sealed.stdout).expect("utf8");

    let opened = hide_desktop_lib::unseal_message_for_tests(
        armored,
        root.join("a.key").display().to_string(),
        None,
    )
    .expect("the desktop app opens a CLI message");
    assert_eq!(opened, "from the command line");
}

#[test]
fn the_cli_opens_what_the_desktop_app_sealed() {
    let Some(cli) = cli() else {
        eprintln!("skipping: the hide CLI has not been built");
        return;
    };
    let directory = tempfile::tempdir().expect("temp dir");
    let root = directory.path();

    // Keys generated by the desktop command this time.
    hide_desktop_lib::generate_keys_for_tests(root.display().to_string(), "ana".into(), None)
        .expect("the desktop command generates keys");
    let armored = hide_desktop_lib::seal_message_for_tests(
        "from the desktop application".into(),
        vec![root.join("ana.hide-pub").display().to_string()],
    )
    .expect("seal");
    std::fs::write(root.join("message.txt"), &armored).expect("write");

    let opened = Command::new(&cli)
        .current_dir(root)
        .args([
            "--experimental",
            "--quiet",
            "unseal",
            "message.txt",
            "--secret",
            "ana.hide-key",
        ])
        .output()
        .expect("cli runs");
    assert!(
        opened.status.success(),
        "{}",
        String::from_utf8_lossy(&opened.stderr)
    );
    assert_eq!(
        String::from_utf8(opened.stdout).expect("utf8").trim_end(),
        "from the desktop application"
    );
}
