[package]
name = "hide-format"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
thiserror.workspace = true
minicbor.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
